name: JHipster Pulsar module CI
on: [push, pull_request]
jobs:
    applications:
        name: generator-jhipster-pulsar test suite
        runs-on: ubuntu-latest
        timeout-minutes: 40
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.13.0
            - name: Install node.js packages
              run: npm install
            - name: Link module
              run: npm link
            - name: Run generator tests
              run: npm test